ARG IMAGE_VER=2.126
FROM jenkins/jenkins:${IMAGE_VER}

ARG chefdkversion=3.0.36
ARG terraformversion=0.11.1
#ARG dockerversion=0.10.8

USER root

RUN apt-get update && apt-get install apt-utils wget python python-pip libssl-dev libffi-dev python-dev build-essential openssl jq \   
    ca-certificates \
    curl \ 
    software-properties-common -y

ADD install-chefdk.sh /usr/local/bin/install-chefdk.sh
RUN chmod +x /usr/local/bin/install-chefdk.sh
RUN /usr/local/bin/install-chefdk.sh ${chefdkversion}

ADD install-terraform.sh /usr/local/bin/install-terraform.sh
RUN chmod +x /usr/local/bin/install-terraform.sh
RUN /usr/local/bin/install-terraform.sh ${terraformversion}

ADD install-azcli.sh /usr/local/bin/install-azcli.sh
#RUN chmod +x /usr/local/bin/install-azcli.sh
#RUN /usr/local/bin/install-azcli.sh

ADD install-azcli.py /usr/local/bin/install-azcli.py
RUN chmod +x /usr/local/bin/install-azcli.py
RUN python /usr/local/bin/install-azcli.py

ADD pipinstall.sh /usr/local/bin/pipinstall.sh
RUN chmod +x /usr/local/bin/pipinstall.sh
RUN /usr/local/bin/pipinstall.sh

ADD create_sslcert.sh /usr/local/bin/create_sslcert.sh
RUN chmod +x /usr/local/bin/create_sslcert.sh
RUN /usr/local/bin/create_sslcert.sh

RUN mkdir -p /home/jenkins/.chef
RUN chown -R jenkins /home/jenkins/.chef

USER jenkins

ENV PATH "$PATH:/usr/local/bin/terraform"
ENV PATH "$PATH:/usr/local/bin/az"

ADD config.json /home/jenkins/.berkshelf/config.json
ADD .chef /home/jenkins/.chef

#RUN cd /home/jenkins && knife ssl fetch

ENTRYPOINT ["tini", "--", "/usr/local/bin/jenkins.sh"]
